version: 0.8.0.{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  secureInfoPassword:
    secure: r5xGVtj4yCfOX7QUsgBCq9IIK2/99/JrSfhmspffhzU=
install:
- ps: .\ci\av-install.ps1
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\ci\av-build.ps1
test:
  categories:
    except:
    - skipCI
    - acmeServerIntegXXX
artifacts:
- path: ACMESharp\ACMESharp\bin
  name: ACME-lib
  type: zip
- path: ACMESharp\ACMESharp.POSH\bin
  name: ACME-posh
  type: zip
- path: ACMESharp\dist\nuget\*.nupkg
  name: ACME-lib-nuget
- path: cov-int
  name: ACMESharp-coverity
  type: zip
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/dc0dd42c91579a605d09
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
on_finish:
- ps: .\ci\av-onfinish.ps1
