version: 0.5.0.{build}
environment:
  secureInfoPassword:
    secure: r5xGVtj4yCfOX7QUsgBCq9IIK2/99/JrSfhmspffhzU=
install:
- nuget restore letsencrypt-win\letsencrypt-win.sln
- nuget install secure-file -ExcludeVersion
- secure-file\tools\secure-file -secret %secureInfoPassword% -decrypt letsencrypt-win\LetsEncrypt.ACME-test\dnsInfo.json.enc
- secure-file\tools\secure-file -secret %secureInfoPassword% -decrypt letsencrypt-win\LetsEncrypt.ACME-test\webServerInfo.json.enc
- secure-file\tools\secure-file -secret %secureInfoPassword% -decrypt letsencrypt-win\LetsEncrypt.ACME-test\testProxyConfig.json.enc
build:
  verbosity: minimal
test:
  categories:
    except:
    - skipCI
artifacts:
- path: letsencrypt-win\LetsEncrypt.ACME\bin
  name: ACME-lib
  type: zip
- path: letsencrypt-win\LetsEncrypt.ACME.POSH\bin
  name: ACME-posh
  type: zip
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/dc0dd42c91579a605d09
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
