version: 0.7.0.{build}
environment:
  secureInfoPassword:
    secure: r5xGVtj4yCfOX7QUsgBCq9IIK2/99/JrSfhmspffhzU=
install:
- nuget restore ACMESharp\ACMESharp.sln
- nuget install secure-file -ExcludeVersion
- secure-file\tools\secure-file -secret %secureInfoPassword% -decrypt ACMESharp\ACMESharp-test\config\dnsInfo.json.enc
- secure-file\tools\secure-file -secret %secureInfoPassword% -decrypt ACMESharp\ACMESharp-test\config\webServerInfo.json.enc
- secure-file\tools\secure-file -secret %secureInfoPassword% -decrypt ACMESharp\ACMESharp-test\config\testProxyConfig.json.enc
build:
  verbosity: minimal
after_build:
- cmd: .\ACMESharp\ACMESharp\mynuget.cmd
test:
  categories:
    except:
    - skipCI
    - acmeServerIntegXXX
artifacts:
- path: ACMESharp\ACMESharp\bin
  name: ACME-lib
  type: zip
- path: ACMESharp\ACMESharp.POSH\bin
  name: ACME-posh
  type: zip
- path: ACMESharp\ACMESharp\bin\nuget\*.nupkg
  name: ACME-lib-nuget
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/dc0dd42c91579a605d09
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
