version: 0.7.0.{build}
environment:
  secureInfoPassword:
    secure: r5xGVtj4yCfOX7QUsgBCq9IIK2/99/JrSfhmspffhzU=
install:
- nuget restore letsencrypt-win\ACMESharp.sln
- nuget install secure-file -ExcludeVersion
- secure-file\tools\secure-file -secret %secureInfoPassword% -decrypt letsencrypt-win\ACMESharp-test\config\dnsInfo.json.enc
- secure-file\tools\secure-file -secret %secureInfoPassword% -decrypt letsencrypt-win\ACMESharp-test\config\webServerInfo.json.enc
- secure-file\tools\secure-file -secret %secureInfoPassword% -decrypt letsencrypt-win\ACMESharp-test\config\testProxyConfig.json.enc
build:
  verbosity: minimal
test:
  categories:
    except:
    - XXXskipCI
artifacts:
- path: letsencrypt-win\ACMESharp\bin
  name: ACME-lib
  type: zip
- path: letsencrypt-win\ACMESharp.POSH\bin
  name: ACME-posh
  type: zip
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/dc0dd42c91579a605d09
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
